### ISSUE TITLE
Plugin does not work with Webpack v4

### ISSUE THREAD

**Issue by Reptarsrage** [langri-sha/screeps-webpack-plugin#40]
ERROR: Plugin could not be registered at 'screeps-webpack-plugin-collect-modules'. Hook was not found.

Stacktrace:
```
Error: Plugin could not be registered at 'screeps-webpack-plugin-collect-modules'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\Tapable.js:63:9)
    at Compilation.deprecated [as plugin] (internal/util.js:47:15)
    at ScreepsWebpackPlugin.registerHandlers (C:\Users\<me>\Documents\Screeps\node_modules\screeps-webpack-plugin\index.js:81:17)
    at compiler.plugin (C:\Users\<me>\Documents\Screeps\node_modules\screeps-webpack-plugin\index.js:33:12)
    at SyncHook.eval [as call] (eval at create (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:11:1)
    at SyncHook.lazyCompileHook [as _call] (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.newCompilation (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:438:26)
    at hooks.beforeCompile.callAsync.err (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:474:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.compile (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:469:28)
    at readRecords.err (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:220:11)
    at Compiler.readRecords (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:342:11)
    at hooks.run.callAsync.err (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:217:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\<me>\Documents\Screeps\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.run (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\Compiler.js:211:24)
    at runWithDependencies (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\MultiCompiler.js:251:15)
    at asyncLib.map (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\MultiCompiler.js:175:6)
    at arrayEachIndex (C:\Users\<me>\Documents\Screeps\node_modules\neo-async\async.js:2539:9)
    at Object.map (C:\Users\<me>\Documents\Screeps\node_modules\neo-async\async.js:2890:9)
    at runCompilers (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\MultiCompiler.js:172:13)
    at MultiCompiler.runWithDependencies (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\MultiCompiler.js:184:3)
    at MultiCompiler.run (C:\Users\<me>\Documents\Screeps\node_modules\webpack\lib\MultiCompiler.js:247:9)
    at processOptions (C:\Users\<me>\Documents\Screeps\node_modules\webpack-cli\bin\webpack.js:510:20)
    at yargs.parse (C:\Users\<me>\Documents\Screeps\node_modules\webpack-cli\bin\webpack.js:513:3)
    at Object.parse (C:\Users\<me>\Documents\Screeps\node_modules\yargs\yargs.js:552:18)
    at C:\Users\<me>\Documents\Screeps\node_modules\webpack-cli\bin\webpack.js:218:8
    at Object.<anonymous> (C:\Users\<me>\Documents\Screeps\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by Reptarsrage** [comment]
This will hopefully be fixed by #38
